# Generated by Django 2.2.3 on 2019-07-09 02:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('effectiveDaye', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
