# Generated by Django 2.2.3 on 2019-07-09 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0002_auto_20190709_0412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='effectiveDaye',
            new_name='effectiveDate',
        ),
    ]
